# Generated by Django 5.0.7 on 2024-10-27 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rol', models.CharField(choices=[('Responsable', 'Responsable'), ('Ejecutor', 'Ejecutor')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('Individual', 'Individual'), ('En equipo', 'En equipo')], max_length=50)),
                ('equipos', models.ManyToManyField(blank=True, related_name='proyectos', to='proyectos.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('inicio', models.DateField()),
                ('termino', models.DateField()),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='proyectos.proyecto')),
                ('ejecutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_ejecutor', to='proyectos.usuario')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_responsable', to='proyectos.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='usuarios',
            field=models.ManyToManyField(related_name='equipos', to='proyectos.usuario'),
        ),
    ]
